# Proyecto UCU

In [ ]:
import shutil
import os
import kagglehub
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Python para Análisis de Datos

#### Análisis de canciones de Spotify

## 1) Definición del Problema

Contamos con un dataset proveniente de Kaggle que se obtuvo utilizando la API de Spotify. Nuestro objetivo será procesarlo para obtener un dataset adecuado que pueda eventualmente entrenar un modelo de Machine Learning para predecir la **POPULARIDAD** de una canción. Intentaremos identificar relaciones entre la **POPULARIDAD** y el resto de los atributos de una determinada canción como lo son la **BAILABILIDAD, ENERGÍA o VOLUMEN**, entre otros.

## Paso 2: Recopilación de datos


Descarga del dataset con kagglehub y guardado en la carpeta _../data/raw_.

### Importación de los datos y creación del DataFrame

In [11]:
path = kagglehub.dataset_download("maharshipandya/-spotify-tracks-dataset")
os.makedirs("../data/raw", exist_ok=True)
shutil.copytree(path, "../data/raw", dirs_exist_ok=True)

display("Spotify Tracks Dataset descargado en: ../data/raw")

'Spotify Tracks Dataset descargado en: ../data/raw'

In [12]:
df = pd.read_csv("../data/raw/dataset.csv")


Exploración de los campos del dataset:

|     Variable     | Definición                                                                                                                       | Key                                                     |
|:----------------:|:---------------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------------------|
|   Unnamed: 0   | Índice del registro                                                                                                              |                                                         |
|     track_id     | Identificador único de la canción                                                                                                |                                                         |
|     artists      | Intérprete/s                                                                                                                     |                                                         |
|    album_name    | Nombre del álbum                                                                                                                 |                                                         |
|    track_name    | Nombre de la canción                                                                                                             |                                                         |
|    popularity    | Popularidad de la canción                                                                                                        | 0 = Menor popularidad, 100 = Mayor popularidad          |
|   duration_ms    | Duración de la canción en milisegundos                                                                                           |                                                         |
|     explicit     | Indica si la canción contiene contenido explícito                                                                                | False = No, True = Sí                                   |
|   danceability   | Bailabilidad (o cualidad de bailable)                                                                                            | 0 = Menos bailable, 1 = Más bailable                    |
|      energy      | Medida de la intensidad de la canción                                                                                            | 0 = Baja energía, 1 = Alta energía                      |
|       key        | Tonalidad en la que está la canción                                                                                              | 0 = C, 1 = C♯/D♭, 2 = D, 3 = D♯/E♭, 4 = E, 5 = F, 6 = F♯/G♭, 7 = G, 8 = G♯/A♭, 9 = A, 10 = A♯/B♭, 11 = B                         |
|     loudness     | Volumen de la canción en decibeles (dB) relativos al máximo digital (0dB)                                                        | Valores que por lo general rondan entre -60 y 0 dB      |
|       mode       | Indica si la tonalidad de la canción está en modo mayor o menor                                                                  | 0 = Menor, 1 = Mayor                                    |
|   speechiness    | Presencia de palabras habladas en la canción                                                                                     | 0 = Poco contenido hablado, 1 = Mucho contenido hablado |
|   acousticness   | Métrica musical que mide el nivel de confianza de que la canción utilice sonidos en vivo en lugar de procesados electrónicamente | 0 = Baja probabilidad, 1 = Alta probabilidad            |
| instrumentalness | Predice si una canción no contiene voces                                                                                         | 0 = Contiene voces, 1 = Instrumental                    |
|     liveness     | Probabilidad de que la grabación haya sido realizada en vivo                                                                     | 0 = Baja probabilidad, 1 = Alta probabilidad            |
|     valence      | Medida que describe la positividad musical de una canción                                                                        | 0 = Más negativa/triste, 1 = Más positiva/alegre        |
|      tempo       | Tempo estimado de la canción en pulsaciones o beats por minuto (BPM)                                                             |                                                         |
|  time_signature  | Compás estimado de la canción                                                                                                    | 3 = 3/4, 4 = 4/4, 5 = 5/4                               |
|   track_genre    | Género musical de la canción                                                                                                     |                                                         |

El dataset provee varios atributos interesantes con los que se pueden estudiar posibles relaciones con la **POPULARIDAD**, nuestra variable objetivo.

## Paso 3: Análisis Descriptivo

In [19]:
df

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

* Se observa que en la columna track_name hay valores duplicados, pero no por error. Para una misma canción el dataset tiene una fila por cada género de la pista.

In [10]:
# Obtenemos el tipo de dato para cada columna.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  str
 2   artists           113999 non-null  str
 3   album_name        113999 non-null  str
 4   track_name        113999 non-null  str
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  str
dtypes: bool(1), float64(9), int64(6), str(5)
memory usage: 26.8 MB

* 3 de las 21 columnas presentan un único dato null.
* El data type detectado para cada columna concuerda con el tipo de dato esperado en todos los casos.

In [18]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,114000.0,56999.500000,32909.109681,0.000,28499.75000,56999.500000,85499.2500,113999.000
popularity,114000.0,33.238535,22.305078,0.000,17.00000,35.000000,50.0000,100.000
duration_ms,114000.0,228029.153114,107297.712645,0.000,174066.00000,212906.000000,261506.0000,5237295.000
danceability,114000.0,0.566800,0.173542,0.000,0.45600,0.580000,0.6950,0.985
energy,114000.0,0.641383,0.251529,0.000,0.47200,0.685000,0.8540,1.000
key,114000.0,5.309140,3.559987,0.000,2.00000,5.000000,8.0000,11.000
loudness,114000.0,-8.258960,5.029337,-49.531,-10.01300,-7.004000,-5.0030,4.532
mode,114000.0,0.637553,0.480709,0.000,0.00000,1.000000,1.0000,1.000
speechiness,114000.0,0.084652,0.105732,0.000,0.03590,0.048900,0.0845,0.965
acousticness,114000.0,0.314910,0.332523,0.000,0.01690,0.169000,0.5980,0.996
instrumentalness,114000.0,0.156050,0.309555,0.000,0.00000,0.000042,0.0490,1.000
liveness,114000.0,0.213553,0.190378,0.000,0.09800,0.132000,0.2730,1.000
valence,114000.0,0.474068,0.259261,0.000,0.26000,0.464000,0.6830,0.995
tempo,114000.0,122.147837,29.978197,0.000,99.21875,122.017000,140.0710,243.372
time_signature,114000.0,3.904035,0.432621,0.000,4.00000,4.000000,4.0000,5.000

* Se detectan algunas incongruencias como los mínimos iguales a 0.000 para duration_ms y tempo. Pasamos a identificarlas:

In [20]:
df[df['duration_ms'] == 0]

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
65900,65900,1kR4gIb7nGxHPI3D2ifs59,NaN,NaN,NaN,0,0,False,0.501,0.583,...,-9.46,0,0.0605,0.69,0.00396,0.0747,0.734,138.391,4,k-pop

In [23]:
df[df['tempo'] == 0]

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
4131,4131,59gg6zQhSKGVnkT3hWAY3l,Max Richter;Lang Lang,Voyager - Essential Max Richter,The Departure,64,151506,False,0.0,0.03620,...,-22.519,0,0.0,0.994000,0.940,0.0958,0.0,0.0,0,ambient
4379,4379,4acmzQsAeMJa5sGFSog7fu,Dario Marianelli;Jack Liebeck;Benjamin Wallfisch,Jane Eyre - Original Motion Picture Soundtrack,The End of Childhood (feat. Jack Liebeck),55,73266,False,0.0,0.04450,...,-26.440,0,0.0,0.972000,0.972,0.0873,0.0,0.0,0,ambient
4664,4664,1Kb2DqjHRvOcT5xeWtz3t5,Sylvain Chauveau,Des Plumes Dans La Tête,Ferme Les Yeux,53,68493,False,0.0,0.03230,...,-23.636,0,0.0,0.994000,0.973,0.0922,0.0,0.0,0,ambient
45670,45670,6B9Mgf9smWqxDjA35VD6MK,Little Symphony,Rialto Beach,Campomoro,22,148711,False,0.0,0.00108,...,-30.204,1,0.0,0.952000,0.991,0.2420,0.0,0.0,0,guitar
45720,45720,7i5OoyPXtSrqz9jobJfG1F,Little Symphony,Rialto Beach,Ritornello,23,102000,False,0.0,0.00129,...,-29.445,1,0.0,0.969000,0.956,0.1230,0.0,0.0,0,guitar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101988,101988,5gEKRH0MCSegG8ZISUPaU2,Granular,The World Of,Tin White Noise,32,182050,False,0.0,0.00002,...,-16.187,1,0.0,0.003850,0.903,0.9210,0.0,0.0,0,sleep
101993,101993,6H0kAiSAFB84jX7dgEDWd6,Rain Sounds,Rain,Rain: Natural Recording,32,84219,False,0.0,0.02540,...,-19.925,1,0.0,0.000002,0.838,0.3390,0.0,0.0,0,sleep
113428,113428,5EYzrykQ95uOmepteDi9KT,El Ruido Blanco;Soñoliento Juan;Mantra para Do...,Aire Acondicionado de Ruido Blanco,Aire de verano,27,128000,False,0.0,0.18800,...,-25.837,0,0.0,0.139000,0.339,0.1220,0.0,0.0,0,world-music
113688,113688,2EnZf7wbFv7ST4CJ3EvNzT,El Ruido Blanco,Ruido Blanco para el bebé: sonidos relajantes ...,Ruido Rosa Puro - Una Hora Versión,24,3601693,False,0.0,0.00002,...,-11.165,1,0.0,0.186000,1.000,0.3620,0.0,0.0,0,world-music
113856,113856,6XsYJ0dwT2hRzp0Qles78F,Колыбельная-земля,Расслабляющие звуки - белый шум для вашего реб...,Пылесос (Белый шум),22,302185,False,0.0,0.22400,...,-10.224,1,0.0,0.142000,0.986,0.4110,0.0,0.0,0,world-music

* La pista con id 65900 debe eliminarse (dato fantasma).
* Existen 157 filas cuyo tempo no pudo ser estimado (y por eso el valor es 0.000)

In [26]:
df.isnull().sum()

track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [27]:
df[df.isnull().any(axis=1)]

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
65900,1kR4gIb7nGxHPI3D2ifs59,NaN,NaN,NaN,0,0,False,0.501,0.583,7,-9.46,0,0.0605,0.69,0.00396,0.0747,0.734,138.391,4,k-pop

In [35]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
113995    False
113996    False
113997    False
113998    False
113999    False
Length: 113422, dtype: bool

In [34]:

df.duplicated(subset=df.columns.difference(['track_id'])).sum()

np.int64(0)

In [7]:
df.columns

Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='str')

### Observaciones:

No se encontraron datos duplicados
se encontro solo 1 registro con valores nulos en 3 campos, por lo que se deberia eliminar a continuacion

## Paso 4: Limpieza de Datos

### Limpieza de datos: Eliminar duplicados

habria que borrar la columna unnamed:0

In [33]:
#df.drop(["Unnamed: 0"], axis=1, inplace=True)
df = df.dropna()

borrada

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
popularity,114000.0,33.238535,22.305078,0.000,17.00000,35.000000,50.0000,100.000
duration_ms,114000.0,228029.153114,107297.712645,0.000,174066.00000,212906.000000,261506.0000,5237295.000
danceability,114000.0,0.566800,0.173542,0.000,0.45600,0.580000,0.6950,0.985
energy,114000.0,0.641383,0.251529,0.000,0.47200,0.685000,0.8540,1.000
key,114000.0,5.309140,3.559987,0.000,2.00000,5.000000,8.0000,11.000
loudness,114000.0,-8.258960,5.029337,-49.531,-10.01300,-7.004000,-5.0030,4.532
mode,114000.0,0.637553,0.480709,0.000,0.00000,1.000000,1.0000,1.000
speechiness,114000.0,0.084652,0.105732,0.000,0.03590,0.048900,0.0845,0.965
acousticness,114000.0,0.314910,0.332523,0.000,0.01690,0.169000,0.5980,0.996
instrumentalness,114000.0,0.156050,0.309555,0.000,0.00000,0.000042,0.0490,1.000
liveness,114000.0,0.213553,0.190378,0.000,0.09800,0.132000,0.2730,1.000
valence,114000.0,0.474068,0.259261,0.000,0.26000,0.464000,0.6830,0.995
tempo,114000.0,122.147837,29.978197,0.000,99.21875,122.017000,140.0710,243.372
time_signature,114000.0,3.904035,0.432621,0.000,4.00000,4.000000,4.0000,5.000

## Paso 5: Análisis de Variables

## Paso 6: Ingeniería de características